### ISSUE TITLE
nim CI doesn't actually test this package

### ISSUE THREAD

**Issue by timotheecour** [dvolk/gnuplot.nim#14]
same issue as https://github.com/tulayang/asyncmysql/issues/5
either a test task needs to be defined or a tests folder needs to exist.
`nim -r c fresnel_test.nim` is not run by nim CI (nor nimble test)

if you need more info, see this other answer: https://github.com/flyx/NimYAML/issues/80#issuecomment-599271895

**Comment by dvolk** [comment]
Thanks for reporting. Fresnel_test.nim is not a unit test. It's an example.
